#!/usr/bin/env bash 

###############################################################################
# This script creates symlinks from the home directory
# to any desired dotfiles in ~/dotfiles
# Thanks to MICHAEL SMALLEY
# (http://blog.smalleycreative.com/tutorials/using-git-and-github-to-manage-your-dotfiles/).
###############################################################################

########## Variables

# dotfiles directory
dir=~/dotfiles

# old dotfiles backup directory
olddir=~/dotfiles_old

# list of files/folders to symlink in homedir
files=("bashrc" "vimrc" "gitignore" "tmux.conf" "tmux" "emacs.d")

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory,
# then create symlinks
for file in ${files[@]}; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done

echo "Installing Vundle."
git clone git@github.com:gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Applying global list of rules for ignoring files in every Git repository."
git config --global core.excludesfile ~/.gitignore

echo "...done"

